global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: node
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - nl_pushgateway:9091
  metric_relabel_configs :
  - regex: exported_job
    action: labeldrop
