{
 "title": "Prometheus Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Remote",
    "query": "nano_block_count{job=~\".*\",type=\"count\"}"
   },
   { "name": "stats_type", "label": "Stats Counters", "query": "nano_stats_counters" },
   { "name": "stats_detail", "label": "Stats Details", "query": "nano_stats_counters" },
   { "name": "stats_dir", "label": "Stats Direction", "query": "in, out" },
   { "name": "stats_objects_l1", "label": "Stats Objects root", "query": "nano_stats_objects_count" }
  ]
 },
 "panels": [
  {
   "title": "Peers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peers",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "count(sum(nano_peers{job=~'${Remote}'}) by(job, endpoint, protocol_version))by (endpoint,protocol_version)"
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nano_node_memory_rss{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}} rss "
      }
     ]
    },
    {
     "title": "RPC Response",
     "type": "table",
     "description": "Method Calls are averaged over all Remotes\nRemotes are averaged over all Methods",
     "gridPos": { "h": 12, "w": 7, "x": 7, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.85, sum (rate(nano_rpc_response_bucket{job=~'${Remote}'}[5m]))by (le, job))",
       "legendFormat": "Job: {{job}}"
      }
     ]
    },
    {
     "title": "RPC Response",
     "type": "table",
     "description": "Method Calls are averaged over all Remotes\nRemotes are averaged over all Methods",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.85, sum (rate(nano_rpc_response_bucket{job=~'${Remote}'}[5m]))by (le, method))",
       "legendFormat": "Method: {{method}}"
      }
     ]
    },
    {
     "title": "Table",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "max(nano_node_peers_stake_total{job=~'${Remote}'})by (job) / 1000000000000000000000000000000"
      },
      {
       "expr": "max(nano_node_online_stake_total{job=~'${Remote}'})by (job) / 1000000000000000000000000000000"
      },
      {
       "expr": "max(nano_node_database{job=~'${Remote}'}) by (job)"
      },
      {
       "expr": "max(nano_node_volume_free{job=~'${Remote}'} / nano_node_volume_total{job=~'${Remote}'} * 100) by (job)"
      },
      {
       "expr": "max(nano_node_volume_free{job=~'${Remote}'}) by (job)"
      },
      {
       "expr": "max(nano_node_frontier_count{job=~'${Remote}'})by (job)"
      }
     ]
    }
   ]
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Block Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nano_block_count{job=~'${Remote}',type=~'cemented|count'}",
     "legendFormat": "{{job}} {{type}}"
    }
   ]
  },
  {
   "title": "Confirmation History avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(nano_confirmation_history{job=~'${Remote}'})without(count)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Blocks/sec ",
   "type": "graph",
   "description": "Blocks per second from block_count RPC",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nano_block_count{job=~'${Remote}',type='cemented'}[30s])",
     "legendFormat": "{{job}} cemented"
    },
    {
     "expr": "rate(nano_block_count{job=~'${Remote}',type='count'}[30s])",
     "legendFormat": "{{job}} count"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads Detail ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
     "repeat": "Remote",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(nano_node_threads{job=~'${Remote}'})by(job,tid)",
       "legendFormat": "{{job}} {{tid}} "
      }
     ]
    },
    {
     "title": "Threads Detail ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(nano_node_threads{job=~'${Remote}'})by(job,tid)",
       "legendFormat": "{{job}} {{tid}} "
      }
     ]
    },
    {
     "title": "Threads Detail ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(nano_node_threads{job=~'${Remote}'})by(job,tid)",
       "legendFormat": "{{job}} {{tid}} "
      }
     ]
    },
    {
     "title": "Threads Detail ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(nano_node_threads{job=~'${Remote}'})by(job,tid)",
       "legendFormat": "{{job}} {{tid}} "
      }
     ]
    },
    {
     "title": "Threads Detail ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(nano_node_threads{job=~'${Remote}'})by(job,tid)",
       "legendFormat": "{{job}} {{tid}} "
      }
     ]
    },
    {
     "title": "Threads Detail ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(nano_node_threads{job=~'${Remote}'})by(job,tid)",
       "legendFormat": "{{job}} {{tid}} "
      }
     ]
    },
    {
     "title": "Threads Detail ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(nano_node_threads{job=~'${Remote}'})by(job,tid)",
       "legendFormat": "{{job}} {{tid}} "
      }
     ]
    },
    {
     "title": "Threads Detail ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(nano_node_threads{job=~'${Remote}'})by(job,tid)",
       "legendFormat": "{{job}} {{tid}} "
      }
     ]
    },
    {
     "title": "Threads Detail ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(nano_node_threads{job=~'${Remote}'})by(job,tid)",
       "legendFormat": "{{job}} {{tid}} "
      }
     ]
    },
    {
     "title": "Threads Detail ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(nano_node_threads{job=~'${Remote}'})by(job,tid)",
       "legendFormat": "{{job}} {{tid}} "
      }
     ]
    },
    {
     "title": "Threads Detail ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(nano_node_threads{job=~'${Remote}'})by(job,tid)",
       "legendFormat": "{{job}} {{tid}} "
      }
     ]
    }
   ]
  },
  {
   "title": "nano_node usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall nano_node usage ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
     "repeat": "Remote",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "nano_node_cpu_usage{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}}"
      }
     ]
    },
    {
     "title": "Overall nano_node usage ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "nano_node_cpu_usage{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}}"
      }
     ]
    },
    {
     "title": "Overall nano_node usage ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "nano_node_cpu_usage{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}}"
      }
     ]
    },
    {
     "title": "Overall nano_node usage ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "nano_node_cpu_usage{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}}"
      }
     ]
    },
    {
     "title": "Overall nano_node usage ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "nano_node_cpu_usage{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}}"
      }
     ]
    },
    {
     "title": "Overall nano_node usage ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "nano_node_cpu_usage{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}}"
      }
     ]
    },
    {
     "title": "Overall nano_node usage ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "nano_node_cpu_usage{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}}"
      }
     ]
    },
    {
     "title": "Overall nano_node usage ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "nano_node_cpu_usage{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}}"
      }
     ]
    },
    {
     "title": "Overall nano_node usage ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "nano_node_cpu_usage{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}}"
      }
     ]
    },
    {
     "title": "Overall nano_node usage ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "nano_node_cpu_usage{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}}"
      }
     ]
    },
    {
     "title": "Overall nano_node usage ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "nano_node_cpu_usage{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}}"
      }
     ]
    }
   ]
  },
  { "title": "Stats Counters Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "${stats_type}/s over 1m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "repeat": "stats_type",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(nano_stats_counters{job=~'${Remote}',type=~'${stats_type}',dir=~'${stats_dir}'}[1m])",
     "legendFormat": "{{job}} {{type}} {{detail}} {{dir}} "
    }
   ]
  },
  {
   "title": "Stats Counters Totals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "${stats_type}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "repeat": "stats_type",
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "nano_stats_counters{job=~'${Remote}',type=~'${stats_type}',dir=~'${stats_dir}'}",
       "legendFormat": "{{job }} {{type}} {{detail}} {{dir}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats Objects Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "${stats_objects_l1}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "repeat": "stats_objects_l1",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nano_stats_objects_count{job=~'${Remote}',l1=~'${stats_objects_l1}'}",
       "legendFormat": "{{job}} {{l1}} {{l2}} {{l3}} count"
      }
     ]
    },
    {
     "title": "${stats_objects_l1}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nano_stats_objects_count{job=~'${Remote}',l1=~'${stats_objects_l1}'}",
       "legendFormat": "{{job}} {{l1}} {{l2}} {{l3}} count"
      }
     ]
    },
    {
     "title": "${stats_objects_l1}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nano_stats_objects_count{job=~'${Remote}',l1=~'${stats_objects_l1}'}",
       "legendFormat": "{{job}} {{l1}} {{l2}} {{l3}} count"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats Objects Count Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "${stats_objects_l1}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "repeat": "stats_objects_l1",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nano_stats_objects_count{job=~'${Remote}',l1=~'${stats_objects_l1}'}[2m])",
       "legendFormat": "{{job}} {{l1}}:{{l2}}:{{l3}}"
      }
     ]
    },
    {
     "title": "${stats_objects_l1}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nano_stats_objects_count{job=~'${Remote}',l1=~'${stats_objects_l1}'}[2m])",
       "legendFormat": "{{job}} {{l1}}:{{l2}}:{{l3}}"
      }
     ]
    },
    {
     "title": "${stats_objects_l1}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nano_stats_objects_count{job=~'${Remote}',l1=~'${stats_objects_l1}'}[2m])",
       "legendFormat": "{{job}} {{l1}}:{{l2}}:{{l3}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats Objects Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "${stats_objects_l1}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "repeat": "stats_objects_l1",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nano_stats_objects_size{job=~'${Remote}',l1=~'${stats_objects_l1}'}",
       "legendFormat": "{{job}} {{l1}}:{{l2}}:{{l3}} size"
      }
     ]
    },
    {
     "title": "${stats_objects_l1}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nano_stats_objects_size{job=~'${Remote}',l1=~'${stats_objects_l1}'}",
       "legendFormat": "{{job}} {{l1}}:{{l2}}:{{l3}} size"
      }
     ]
    },
    {
     "title": "${stats_objects_l1}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nano_stats_objects_size{job=~'${Remote}',l1=~'${stats_objects_l1}'}",
       "legendFormat": "{{job}} {{l1}}:{{l2}}:{{l3}} size"
      }
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version Info",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "count (nano_version_info) by (job,build_info,network,network_identifier,node_vendor,protocol_version,rpc_version,store_vendor,store_version)",
       "legendFormat": "{{job}} {{build_info}} {{node_vendor}} {{protocol_version}} {{rpc_version}} {{store_vendor}} {{store_version}} {{network}} {{network_identifier}}"
      }
     ]
    }
   ]
  }
 ]
}