{
 "title": "Node Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "nano_block_count{job=~\".*\",type=\"count\"}"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "nano_block_count{job=~\".*\",type=\"count\"}"
    }
   },
   { "name": "stats_type", "label": "Stats Counters", "query": { "query": "nano_stats_counters" } },
   { "name": "stats_detail", "label": "Stats Details", "query": { "query": "nano_stats_counters" } },
   { "name": "stats_dir", "label": "Stats Direction", "query": "in, out" },
   { "name": "stats_objects_l1", "label": "Stats Objects root", "query": { "query": "nano_stats_objects_count" } },
   {
    "name": "Blocks",
    "query": {
     "query": "nano_block_count{job=~\".*\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Peers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Peers",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "count(sum(telemetry_raw_peer{job='${Job}', instance='${Instance}'}) by(job, instance, endpoint, protocol_version)) by (instance, endpoint,protocol_version)"
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nano_node_memory_rss{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}} rss "
      }
     ]
    },
    {
     "title": "RPC Response",
     "type": "table-old",
     "description": "Method Calls are averaged over all Remotes\nRemotes are averaged over all Methods",
     "gridPos": { "h": 12, "w": 7, "x": 7, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.85, sum (rate(nano_rpc_response_bucket{job=~'${Remote}'}[5m]))by (le, job))",
       "legendFormat": "Job: {{job}}"
      }
     ]
    },
    {
     "title": "RPC Response",
     "type": "table-old",
     "description": "Method Calls are averaged over all Remotes\nRemotes are averaged over all Methods",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.85, sum (rate(nano_rpc_response_bucket{job=~'${Remote}'}[5m]))by (le, method))",
       "legendFormat": "Method: {{method}}"
      }
     ]
    },
    {
     "title": "Table",
     "type": "table-old",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "max(nano_node_peers_stake_total{job=~'${Remote}'})by (job) / 1000000000000000000000000000000"
      },
      {
       "expr": "max(nano_node_online_stake_total{job=~'${Remote}'})by (job) / 1000000000000000000000000000000"
      },
      {
       "expr": "max(nano_node_database{job=~'${Remote}'}) by (job)"
      },
      {
       "expr": "max(nano_node_volume_free{job=~'${Remote}'} / nano_node_volume_total{job=~'${Remote}'} * 100) by (job)"
      },
      {
       "expr": "max(nano_node_volume_free{job=~'${Remote}'}) by (job)"
      },
      {
       "expr": "max(nano_node_frontier_count{job=~'${Remote}'})by (job)"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time since last data update",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - push_time_seconds{job='${Job}', instance=~'${Instance}'}",
     "legendFormat": "[ {{instance}} ]"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nano_node_peer_count{job='${Job}', instance=~'${Instance}'}",
     "legendFormat": "[ {{instance}} ]"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nano_block_count{job='${Job}', instance=~'${Instance}', type=~'${Blocks}'}",
     "legendFormat": "[ {{instance}} ] {{type}}"
    }
   ]
  },
  {
   "title": "Blocks/sec ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv(nano_block_count{job='${Job}', instance=~'${Instance}', type=~'${Blocks}'}[60s])",
     "legendFormat": "[ {{instance}} ] {{type}}"
    }
   ]
  },
  {
   "title": "TX/RX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "TX/s over 1m",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(network_raw_tx{job='${Job}', instance=~'${Instance}'}[1m])",
       "legendFormat": "[ {{instance}} ] tx"
      }
     ]
    },
    {
     "title": "RX/s over 1m",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(network_raw_rx{job='${Job}', instance=~'${Instance}'}[1m])",
       "legendFormat": "[ {{instance}} ] rx"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${Instance}",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
     "repeat": "Instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nano_node_threads{job=~'${Job}', instance=~'${Instance}'}",
       "legendFormat": "{{name}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Stats Objects Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_objects_l1}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "repeat": "stats_objects_l1",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nano_stats_objects_count{job='${Job}', instance=~'${Instance}',l1=~'${stats_objects_l1}'}",
       "legendFormat": "[ {{instance}} ] {{l1}} : {{l2}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats Counters Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_type}/s over 1m",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "repeat": "stats_type",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(nano_stats_counters{job='${Job}', instance=~'${Instance}',type=~'${stats_type}',dir=~'${stats_dir}',detail=~'${stats_detail}'}[1m])",
       "legendFormat": "[ {{instance}} ] {{type}} : {{detail}} : {{dir}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Confirmation History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Confirmation History avg",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(nano_confirmation_history{job='${Job}', instance=~'${Instance}'})without(count)",
       "legendFormat": "[ {{instance}} ]"
      }
     ]
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Buckets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "nano_stats_objects_count{job='${Job}',instance=~'${Instance}',l1=~'election_scheduler',l2=~'priority'}",
       "legendFormat": "[ {{instance}} ] {{l3}}"
      }
     ]
    }
   ]
  },
  {
   "title": "nano_node usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Overall nano_node usage ${Remote}",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 43 },
     "repeat": "Remote",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "nano_node_cpu_usage{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats Counters Totals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_type}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 209 },
     "repeat": "stats_type",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "nano_stats_counters{job='${Job}', instance=~'${Instance}',type=~'${stats_type}',dir=~'${stats_dir}'}",
       "legendFormat": "[ {{instance}} ] {{type}} : {{detail}} : {{dir}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats Objects Count Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_objects_l1}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 210 },
     "repeat": "stats_objects_l1",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nano_stats_objects_count{job='${Job}', instance=~'${Instance}',l1=~'${stats_objects_l1}'}[2m])",
       "legendFormat": "[ {{instance}} ] {{l1}} : {{l2}} : {{l3}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats Objects Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_objects_l1}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 211 },
     "repeat": "stats_objects_l1",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nano_stats_objects_size{job='${Job}', instance=~'${Instance}',l1=~'${stats_objects_l1}'}",
       "legendFormat": "{{instance}} {{l1}}:{{l2}}:{{l3}} size"
      }
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version Info",
   "type": "table-old",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "count (nano_version_info{job='${Job}', instance=~'${Instance}'}) by (instance,build_info,network,network_identifier,node_vendor,protocol_version,rpc_version,store_vendor,store_version)",
     "legendFormat": "{{job}} {{build_info}} {{node_vendor}} {{protocol_version}} {{rpc_version}} {{store_vendor}} {{store_version}} {{network}} {{network_identifier}}"
    }
   ]
  }
 ]
}