genesis_key = "12C91837C846F875F56F67CD83040A832CFC0F131AF3DFF9E502C0D43F5D2D14" #initial_balance = 340282366920938463463374607431768211455
canary_key = "FB4E458CB13508353C5B2574B82F1D1D61367F61E88707F773F068FF90050BEA"
epoch_count = 2 
burn_amount = "200000000000000000000000000000000000000" #sent to xrb_1111111111111111111111111111111111111111111111111111hifc8npp

##### NANO NODE ENV VARIABLES ####
#NANO_TEST_EPOCH_1="0x00000000000fff00" #this is fixed to 0x000000000000000f
NANO_TEST_EPOCH_2="0xffffc00000ffff00" #optional overrides dc_nano_local_env
NANO_TEST_EPOCH_2_RECV="0xffffc00000ffff00" #optional overrides dc_nano_local_env
NANO_TEST_MAGIC_NUMBER="LC" #optional overrides dc_nano_local_env


[representatives]
    #### shared config between all reps
    config_node_path = "./default_config-node.toml" #optional if you want to modify parameters
    config_rpc_path = "./default_config-rpc.toml" #optional if you want to modify parameters

    ### Choose between --docker_tag (existing tag  --nano_node_path
    #https://hub.docker.com/r/nanocurrency/nano-test/tags
    docker_tag = "latest" #shared between all nodes 
    #nano_node_path = "/path/to/nano_node"   #path to nano_node executable  

#### individual node settings
[[representatives.nodes]] 
    name = "nl_pr1"
    seed = "1110000000000000000000000000000000000000000000000000000000000001"

    ### Chose between -balance or -vote_weight_percent
    balance = "43000000000000000000000000000000000000"   #final node balance
    #vote_weight_percent = 35   
   
    ### Choose between --docker_tag (existing tag  --nano_node_path
    #docker_tag = "V22.1"  #overrides shared property representatives.docker_tag
    #nano_node_path = "/path/to/nano_node"   #path to executable

    #config_node_path = "./default_config-node.toml" #overrides shared property representatives.config_node_path
    #config_rpc_path = "./default_config-rpc.toml"  #overrides shared property representatives.config_rpc_path

[[representatives.nodes]] 
    name = "nl_pr2"
    seed = "1110000000000000000000000000000000000000000000000000000000000002" 
    vote_weight_percent = 35  

[[representatives.nodes]] 
    name = "nl_node3"
    seed = "1110000000000000000000000000000000000000000000000000000000000003"   
    vote_weight_percent = 0.05