[node.websocket]
address = "::ffff:0.0.0.0"
# Enable or disable WebSocket server.
enable = true
port = 17078

[rpc]
enable = true
enable_sign_hash = true

[node]
work_threads = 1
enable_voting = false
peering_port = 17075
preconfigured_peers = []
allow_local_peers = true
#bandwidth_limit = 4096


