name: Run nano-local tests



on:
   push:
     branches: [ "work_flow_test" ]

permissions:
   contents: read

jobs:
   build:

     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v3
     - name: Set up Python 3.8.10
       uses: actions/setup-python@v3
       with:
         python-version: "3.8.10"
     - name: setup venv
       run: ./venv_nano_local.sh
     - name: setup nano-local network
       run: |
         ./run_nano_local.py create 
         ./run_nano_local.py start
         ./run_nano_local.py init
     - name: wait for nodes to sync
       run: ./run_nano_local.py restart_wait_sync
     - name: run testcases
       run: ./run_nano_local.py pytest