name: run nano-local testsuite



on:
   push:
     branches: [ "main" ]

permissions:
   contents: read

jobs:
   build:

     runs-on: self-hosted

     steps:
     - uses: actions/checkout@v3
     - name: Set up Python 3.8.10
       uses: actions/setup-python@v3
       with:
         python-version: "3.8.10"
     - name: setup venv
       run: ./venv_nano_local.sh
     - name: setup nano-local network
       run: |
         ./nl_run.py.py create 
         ./nl_run.py.py start
         ./nl_run.py.py init
     - name: wait for nodes to sync
       run: ./nl_run.py.py restart_wait_sync
     - name: run testcases
       run: ./nl_run.py.py pytest