name: run nano-local testsuite



on:
   push:
     branches: [ "main" ]

permissions:
   contents: read

jobs:
   build:

     runs-on: ubuntu-22.04

     steps:
     - uses: actions/checkout@v3
     - name: Set up Python 3.8.15
       uses: actions/setup-python@v3
       with:
         python-version: "3.8.15"
     - name: setup venv
       run: ./setup_python_venv.sh
     - name: setup nano-local network
       run: |
         ./nl_run.py create 
         ./nl_run.py start
         ./nl_run.py init
     - name: wait for nodes to sync
       run: ./nl_run.py restart_wait_sync
     - name: run testcases
       run: ./nl_run.py pytest